import os
import ctypes
import time
import random

ctypes.windll.kernel32.SetConsoleTitleW("Command Prompt")

user = os.getlogin()
unstopped = True

def n():
    print()

def shell():
    # Display shell prompt with the current directory and take user input
    print("")
    return input(f"{os.getcwd()}>")

def thatdidntwork():
    print(f"'{choice}' is not recognized as an internal or external command,")
    print("operable program or batch file.")

print("Microsoft Windows [Version 10.0.22631.4391]")
print("(c) Microsoft Corporation. All rights reserved.")

while True:
    choice = shell()

    if choice == "":
        continue

    if choice == "exit":
        exit()

    elif choice == "cls": 
        os.system("cls")

    elif choice == "dir":
        os.system("dir")
        print("All files scanned to be safe!")

    elif choice.startswith("echo"):
        message = choice[len("echo "):]
        print(message)

    elif choice.startswith("cd"):
        try:
            path = choice[3:].strip()
            if path == "":
                os.chdir(os.path.expanduser("~"))
            else:
                os.chdir(path)
                
        except FileNotFoundError:
            print(f"The system cannot find the path specified: '{path}'")

    elif choice == "tree":
        willitrun = random.randint(0,7)
        if willitrun > 1:
            print("Scanning...")
            time.sleep(1)
            print("Folder PATH listing")
            print("Volume serial number is 725A-D6A8")
            print("C:.")
            print("├───.android")
            print("├───.ccp")
            print("├───.dotnet")
            print("│   └───TelemetryStorageService")
            time.sleep(0.1)
            print("├───.e4mc_cache")
            print("├───.gradle")
            print("│   └───daemon")
            print("│       └───8.7")
            print("├───.idlerc")
            print("├───.mcreator")
            print("│   ├───backgrounds")
            print("│   ├───gradle")
            print("│   │   ├───.tmp")
            print("│   │   │   └───.cache")
            print("│   │   │       └───expanded")
            print("│   │   │           ├───zip_047b67fbde31e75036d0278d90629054")
            time.sleep(0.1)
            print("│   │   │           ├───zip_073dc9a145c34d5e7fcd73c73e2804b5")
            print("│   │   │           ├───zip_09b1634b5d1234c758e1cb8527ef3105")
            print("│   │   │           ├───zip_0de52fe13d81a0099bb3e3fe3808ad60")
            print("│   │   │           ├───zip_1171a7a4157c3beccf10884eb68d853e")
            print("│   │   │           ├───zip_17d391a08cc0ac747dfbb35659102e51")
            print("│   │   │           ├───zip_19d161fd3598aafecef5f0830ea78d14")
            print("│   │   │           ├───zip_19da7570be7912322fe37572d1a6810f")
            print("│   │   │           ├───zip_1a70978f483a50c05d94ed3cfca15302")
            print("│   │   │           ├───zip_229864c7d31171e01fdbea05c9195a7e")
            print("│   │   │           ├───zip_234f31f2d7b254e817afaa96249d7d89")
            print("│   │   │           ├───zip_26bbf3aac563ff0c98e45e4e97ecfd03")
            print("│   │   │           ├───zip_276009ee0660417fa7d2939edd19174f")
            print("│   │   │           ├───zip_2aee1f5ad01f7e90655a3e0f9af640f3")
            print("│   │   │           ├───zip_2b8d73e9803166a17ea4a08457cf228b")
            print("│   │   │           ├───zip_2c002f003f13dfede7a4f62fb18e27db")
            print("│   │   │           ├───zip_2cc56b2af9831c44fe773a69544dbdc6")
            print("│   │   │           ├───zip_2e0e2b44b2c013995a90d87904f74891")
            print("│   │   │           ├───zip_320f4c3e5dd9c0b21a8cbecae29c7129")
            print("│   │   │           ├───zip_34140a8765f98b376d9b2185b7eb7ab3")
            print("│   │   │           ├───zip_34d95c8419e0478c6eca2231ca8b47be")
            print("│   │   │           ├───zip_36b934086ff255e111d8df187291ee81")
            print("│   │   │           ├───zip_36c485f0ca1e4bf167f723132dc1fb65")
            print("│   │   │           ├───zip_36e1a859a8e611f890b202b3d79bae7b")
            print("│   │   │           ├───zip_3a8b7706111b6cb226f4b68e7836858d")
            print("│   │   │           ├───zip_41e5bada02bbdc23e2e456291de551f2")
            print("│   │   │           ├───zip_455c0b2b95381aaa769345a6ea237d94")
            print("│   │   │           ├───zip_4c935c1503a85b1f14c48599c2a220e5")
            print("│   │   │           ├───zip_4d0c6394faf9ac0a70ec8adc3779a767")
            print("│   │   │           ├───zip_4ebe409f5f34aac720db21fdcb3eeb1e")
            print("│   │   │           ├───zip_52a74bff37a3f4019ee4eeff240ab5dc")
            print("│   │   │           ├───zip_547466f8f43f8c832604228e4364649c")
            print("│   │   │           ├───zip_551483c776082be39e7e69b3a66ca09d")
            print("│   │   │           ├───zip_55436daa092722bf85fc2473d4f327c9")
            print("│   │   │           ├───zip_56f5c33cc507c1f762b11aff06da68f3")
            print("│   │   │           ├───zip_5b0003d72a16e11fb527fb65d33d1f03")
            print("│   │   │           ├───zip_5c4c4a8db339f1e77be7c0b697f84c6d")
            print("│   │   │           ├───zip_5c9ab0b493d73ffb7318975e37221a9b")
            print("│   │   │           ├───zip_5f8a213d33e8205786913026b724f861")
            print("│   │   │           ├───zip_6069d43c728d593fb43038dd0aa13fcc")
            print("│   │   │           ├───zip_60d8e6190f8a98e158fcb6ef70a5bcf2")
            print("│   │   │           ├───zip_65592087babb7093568ab5075dcaf103")
            print("│   │   │           ├───zip_65bf4a89f4a0d5e065b8b5b849ff015e")
            print("│   │   │           ├───zip_6618b591583f9cb87f65d6b59ffa5997")
            print("│   │   │           ├───zip_6674bb4c5aca4390d60b07de4d84592e")
            print("│   │   │           ├───zip_66a96d3485ec0550c16cc10dbf290566")
            print("│   │   │           ├───zip_676502372eafffa3228d01864fcbdfb2")
            print("│   │   │           ├───zip_68c4f629585b2e1abb0b744a4938d5d5")
            print("│   │   │           ├───zip_6c9c92bc74193489f980a8eb1ce97bef")
            print("│   │   │           ├───zip_6cb8ef69f94fb5ba5f7125b51729e094")
            print("│   │   │           ├───zip_6cd5201fc97df6c7b7168c8f5c298b1e")
            print("│   │   │           ├───zip_6e7fd44889a4e245d1c10bf23243cda4")
            print("│   │   │           ├───zip_6f0c81203172ad5b896ee6fd036ca4ee")
            print("│   │   │           ├───zip_701e1668c3181d078253c2592842f948")
            print("│   │   │           ├───zip_772fc2a6f48ed2e8a7f69123943255c9")
            print("│   │   │           ├───zip_7cbdebf1d396ad51dd06d033247226f9")
            print("│   │   │           ├───zip_7f2c19531558b795526dd961c7db2077")
            print("│   │   │           ├───zip_810224a7c05c7e25657e68811db8e197")
            print("│   │   │           ├───zip_82d86653020f9d274766516c5b25a7ee")
            print("│   │   │           ├───zip_83b6ec896e91769c3923938e323eac53")
            print("│   │   │           ├───zip_85cd0fb49ffbbbc23212f852d5a18437")
            print("│   │   │           ├───zip_88de945fc1ea882c7b585ec6c5f001d5")
            print("│   │   │           ├───zip_8b5e2b488e6c9cc8d3518944391b6e1e")
            print("│   │   │           ├───zip_8cba60dbb69fc42d7c9046957ae6b08f")
            print("│   │   │           ├───zip_8ce1c345209000e9d7962c85a911df24")
            print("│   │   │           ├───zip_8e25d6cd1758debd589c822f64236436")
            print("│   │   │           ├───zip_9274697aa81e3a8f9b480744711b56a6")
            print("│   │   │           ├───zip_92da27eb4988c16ae65a5a0da0e5be4e")
            print("│   │   │           ├───zip_931348f95609fa8afccc8c55e0aae38f")
            print("│   │   │           ├───zip_95fbfd047b44dd69abd30be30221876f")
            print("│   │   │           ├───zip_9a6261edf9bcbc077464b892e0652bbd")
            print("│   │   │           ├───zip_9c90eeaaa22bde0d26f7d04cad870838")
            print("│   │   │           ├───zip_9e0f2bdbb5e23289b13058e850ffa8fb")
            print("│   │   │           ├───zip_9f8f2e37a112d15e493cafb02ec70a36")
            print("│   │   │           ├───zip_9fc93e274cee3f9a6118af4f097a98fd")
            print("│   │   │           ├───zip_a0129c42993f18db7125b5e11ac3bb63")
            print("│   │   │           ├───zip_a0d7c50cd166795b29229c12c2d18715")
            print("│   │   │           ├───zip_a109d4cd66e7d977602b14c2d4f374ba")
            print("│   │   │           ├───zip_a1e9552625766484832b1e126744b644")
            print("│   │   │           ├───zip_a56ee5745e5922f00bb1a07087d2028a")
            print("│   │   │           ├───zip_ab34525a464549ad8c2f630198a1918f")
            print("│   │   │           ├───zip_b1e25afa69ea9d4c1708dbf469630159")
            print("│   │   │           ├───zip_ba243bf4d98781f4c400d406a272b932")
            print("│   │   │           ├───zip_bb6a3706d9a3cc093b1af89ae12d3bae")
            print("│   │   │           ├───zip_bc56eac4f5597788b7e429c6bdf5548c")
            print("│   │   │           ├───zip_bdccd61bd8e5a30b1591a66511127d12")
            print("│   │   │           ├───zip_c474ebcffc13856bbc027548d086de75")
            print("│   │   │           ├───zip_c59e2b2bb3b90f57e39565032bb5b343")
            print("│   │   │           ├───zip_c779c02909760922d517a052c7e940cc")
            print("│   │   │           ├───zip_c806178912f8319b74d57f11f5ce0720")
            print("│   │   │           ├───zip_cc316803f8b8c4bd3f17c755532ad1f2")
            print("│   │   │           ├───zip_d0f06c8d344499ed6efad0a27cfd7932")
            print("│   │   │           ├───zip_d4b7a2298e6e6494665852ce878a50d0")
            print("│   │   │           ├───zip_d764905413ef28d03786b09ddbc19e4b")
            print("│   │   │           ├───zip_d9798f66e2a4d6be875f9fe432426a62")
            print("│   │   │           ├───zip_da4ac78d6e4c74bc4d270089bf567bdc")
            print("│   │   │           ├───zip_dac155692774012c41d356387d81ad35")
            print("│   │   │           ├───zip_db4efc89ca954fb1e6e1509b490c6d1f")
            print("│   │   │           ├───zip_dff54fc56b10b2c675c93509a49bcd78")
            print("│   │   │           ├───zip_e2f75a925cab4f9ee7e9e9d6569fbc85")
            print("│   │   │           ├───zip_e34f27545322f6b278f32989c08dfd26")
            print("│   │   │           ├───zip_e49e124a21b139fb753365b99fa54b06")
            print("│   │   │           ├───zip_e545b201b479d33a3caeb7f106c7f20c")
            print("│   │   │           ├───zip_e6cf901783dc25e062ae754eb5e54f2c")
            print("│   │   │           ├───zip_e84de9c031dca5f9c0de955404120fe4")
            print("│   │   │           ├───zip_e85d9fcab48c352cd085122eddff6758")
            print("│   │   │           ├───zip_ebc1c3c9f503921d19e9a92ce9ed6d8b")
            print("│   │   │           ├───zip_ed3e6258aad2db2fbeb567103b3f69d1")
            print("│   │   │           ├───zip_ed4300ab33e72f163479fb992e127243")
            print("│   │   │           ├───zip_f4aaa49a97efb15ced19c3416f9f05b1")
            print("│   │   │           ├───zip_f505588d151645317b7652f7b26a1f8a")
            time.sleep(0.1)
            print("│   │   │           ├───zip_fb5bb772c475985b40616b923459bebf")
            print("│   │   │           └───zip_fd57c8c766b4bf08671068882fa0b077")
            print("│   │   ├───caches")
            print("│   │   │   ├───8.7")
            print("│   │   │   │   ├───file-changes")
            print("│   │   │   │   ├───fileContent")
            print("│   │   │   │   ├───fileHashes")
            print("│   │   │   │   ├───generated-gradle-jars")
            print("│   │   │   │   ├───groovy-dsl")
            print("│   │   │   │   │   ├───050fdec6c6bd84dcf5025e749b6793c6")
            print("│   │   │   │   │   │   ├───classes")
            print("│   │   │   │   │   │   │   └───proj")
            print("│   │   │   │   │   │   ├───instrumented")
            print("│   │   │   │   │   │   └───metadata")
            print("│   │   │   │   │   ├───0cdee5a6d36d8877152aab0cc7ad92fc")
            print("│   │   │   │   │   │   ├───classes")
            print("│   │   │   │   │   │   │   └───cp_proj")
            print("│   │   │   │   │   │   ├───instrumented")
            print("│   │   │   │   │   │   └───metadata")
            print("│   │   │   │   │   ├───1f14b5dbea80b8b883f6c9d8b606ec9c")
            print("│   │   │   │   │   │   ├───classes")
            print("│   │   │   │   │   │   │   └───settings")
            print("│   │   │   │   │   │   ├───instrumented")
            print("│   │   │   │   │   │   └───metadata")
            print("│   │   │   │   │   └───f2d00071ab6d5a704de461a121fb523b")
            print("│   │   │   │   │       ├───classes")
            print("│   │   │   │   │       │   └───cp_settings")
            print("│   │   │   │   │       ├───instrumented")
            print("│   │   │   │   │       └───metadata")
            print("│   │   │   │   ├───javaCompile")
            print("│   │   │   │   ├───md-rule")
            print("│   │   │   │   ├───md-supplier")
            print("│   │   │   │   └───workerMain")
            print("│   │   │   ├───jars-9")
            print("│   │   │   │   ├───3075872a60a67b053c24e96103bb17e6")
            print("│   │   │   │   ├───5ff894fade7f891ddbffbb6fcad185b9")
            print("│   │   │   │   ├───7dfe225faf9938c36acc3cd9b62b498b")
            print("│   │   │   │   └───f3c4368df46e18a2b3b7a9774b3e6b9e")
            print("│   │   │   ├───journal-1")
            print("│   │   │   ├───minecraft")
            print("│   │   │   │   ├───assets")
            print("│   │   │   │   │   └───1.20.4")
            print("│   │   │   │   ├───libraries")
            print("│   │   │   │   │   ├───ca")
            print("│   │   │   │   │   │   └───weblite")
            print("│   │   │   │   │   │       └───java-objc-bridge")
            print("│   │   │   │   │   │           └───1.1")
            print("│   │   │   │   │   ├───com")
            print("│   │   │   │   │   │   ├───github")
            print("│   │   │   │   │   │   │   └───oshi")
            print("│   │   │   │   │   │   │       └───oshi-core")
            print("│   │   │   │   │   │   │           └───6.4.5")
            print("│   │   │   │   │   │   ├───google")
            print("│   │   │   │   │   │   │   ├───code")
            print("│   │   │   │   │   │   │   │   └───gson")
            print("│   │   │   │   │   │   │   │       └───gson")
            print("│   │   │   │   │   │   │   │           └───2.10.1")
            print("│   │   │   │   │   │   │   └───guava")
            print("│   │   │   │   │   │   │       ├───failureaccess")
            print("│   │   │   │   │   │   │       │   └───1.0.1")
            print("│   │   │   │   │   │   │       └───guava")
            print("│   │   │   │   │   │   │           └───32.1.2-jre")
            print("│   │   │   │   │   │   ├───ibm")
            print("│   │   │   │   │   │   │   └───icu")
            print("│   │   │   │   │   │   │       └───icu4j")
            print("│   │   │   │   │   │   │           └───73.2")
            print("│   │   │   │   │   │   └───mojang")
            print("│   │   │   │   │   │       ├───authlib")
            print("│   │   │   │   │   │       │   └───6.0.52")
            print("│   │   │   │   │   │       ├───blocklist")
            print("│   │   │   │   │   │       │   └───1.0.10")
            print("│   │   │   │   │   │       ├───brigadier")
            print("│   │   │   │   │   │       │   └───1.2.9")
            print("│   │   │   │   │   │       ├───datafixerupper")
            print("│   │   │   │   │   │       │   └───6.0.8")
            print("│   │   │   │   │   │       ├───logging")
            print("│   │   │   │   │   │       │   └───1.1.1")
            print("│   │   │   │   │   │       ├───patchy")
            print("│   │   │   │   │   │       │   └───2.2.10")
            print("│   │   │   │   │   │       └───text2speech")
            print("│   │   │   │   │   │           └───1.17.9")
            print("│   │   │   │   │   ├───commons-codec")
            print("│   │   │   │   │   │   └───commons-codec")
            print("│   │   │   │   │   │       └───1.16.0")
            print("│   │   │   │   │   ├───commons-io")
            print("│   │   │   │   │   │   └───commons-io")
            print("│       │   │       │   │   │               │       └───chunk")
            print("│       │   │       │   │   │               ├───data")
            print("│       │   │       │   │   │               │   ├───event")
            print("│       │   │       │   │   │               │   └───loading")
            print("│       │   │       │   │   │               ├───energy")
            print("│       │   │       │   │   │               ├───entity")
            print("│       │   │       │   │   │               ├───event")
            print("│       │   │       │   │   │               │   ├───brewing")
            print("│       │   │       │   │   │               │   ├───enchanting")
            print("│       │   │       │   │   │               │   ├───entity")
            print("│       │   │       │   │   │               │   │   ├───item")
            print("│       │   │       │   │   │               │   │   ├───living")
            print("│       │   │       │   │   │               │   │   └───player")
            print("│       │   │       │   │   │               │   ├───furnace")
            print("│       │   │       │   │   │               │   ├───level")
            print("│       │   │       │   │   │               │   ├───server")
            print("│       │   │       │   │   │               │   └───village")
            print("│       │   │       │   │   │               ├───fluids")
            print("│       │   │       │   │   │               │   └───capability")
            print("│       │   │       │   │   │               │       ├───templates")
            print("│       │   │       │   │   │               │       └───wrappers")
            print("│       │   │       │   │   │               ├───forge")
            print("│       │   │       │   │   │               │   └───snapshots")
            print("│       │   │       │   │   │               ├───gametest")
            print("│       │   │       │   │   │               ├───internal")
            print("│       │   │       │   │   │               │   └───versions")
            time.sleep(0.1)
            print("│       │   │       │   │   │               │       ├───neoforge")
            print("│       │   │       │   │   │               │       └───neoform")
            print("│       │   │       │   │   │               ├───items")
            print("│       │   │       │   │   │               │   └───wrapper")
            print("│       │   │       │   │   │               ├───logging")
            print("│       │   │       │   │   │               ├───network")
            print("│       │   │       │   │   │               │   ├───bundle")
            print("│       │   │       │   │   │               │   ├───configuration")
            print("│       │   │       │   │   │               │   ├───connection")
            print("│       │   │       │   │   │               │   ├───event")
            print("│       │   │       │   │   │               │   ├───filters")
            print("│       │   │       │   │   │               │   ├───handlers")
            print("│       │   │       │   │   │               │   ├───handling")
            print("│       │   │       │   │   │               │   ├───negotiation")
            print("│       │   │       │   │   │               │   ├───payload")
            print("│       │   │       │   │   │               │   └───registration")
            print("│       │   │       │   │   │               ├───registries")
            print("│       │   │       │   │   │               │   ├───callback")
            print("│       │   │       │   │   │               │   ├───datamaps")
            print("│       │   │       │   │   │               │   │   └───builtin")
            print("│       │   │       │   │   │               │   └───holdersets")
            print("│       │   │       │   │   │               ├───resource")
            print("│       │   │       │   │   │               └───server")
            print("│       │   │       │   │   │                   ├───command")
            print("│       │   │       │   │   │                   │   └───generation")
            print("│       │   │       │   │   │                   ├───console")
            print("│       │   │       │   │   │                   ├───loading")
            print("│       │   │       │   │   │                   ├───permission")
            print("│       │   │       │   │   │                   │   ├───events")
            print("│       │   │       │   │   │                   │   ├───exceptions")
            print("│       │   │       │   │   │                   │   ├───handler")
            print("│       │   │       │   │   │                   │   └───nodes")
            print("│       │   │       │   │   │                   └───timings")
            print("│       │   │       │   │   └───generated")
            print("│       │   │       │   │       └───sources")
            print("│       │   │       │   │           ├───annotationProcessor")
            print("│       │   │       │   │           └───headers")
            print("│       │   │       │   ├───rename")
            print("│       │   │       │   ├───stripClient")
            print("│       │   │       │   └───stripServer")
            print("│       │   │       └───unpacked")
            print("│       │   │           ├───config")
            print("│       │   │           │   └───inject")
            print("│       │   │           │       └───mcp")
            print("│       │   │           │           └───client")
            print("│       │   │           └───patches")
            print("│       │   │               ├───client")
            print("│       │   │               │   ├───com")
            print("│       │   │               │   │   └───mojang")
            print("│       │   │               │   │       ├───blaze3d")
            print("│       │   │               │   │       │   └───platform")
            print("│       │   │               │   │       └───realmsclient")
            print("│       │   │               │   │           └───gui")
            print("│       │   │               │   │               └───screens")
            print("│       │   │               │   └───net")
            print("│       │   │               │       └───minecraft")
            print("│       │   │               │           ├───advancements")
            print("│       │   │               │           │   └───critereon")
            print("│       │   │               │           ├───client")
            print("│       │   │               │           │   ├───gui")
            print("│       │   │               │           │   │   ├───components")
            print("│       │   │               │           │   │   ├───screens")
            print("│       │   │               │           │   │   │   ├───achievement")
            print("│       │   │               │           │   │   │   ├───multiplayer")
            print("│       │   │               │           │   │   │   ├───reporting")
            print("│       │   │               │           │   │   │   ├───telemetry")
            print("│       │   │               │           │   │   │   └───worldselection")
            print("│       │   │               │           │   │   └───spectator")
            print("│       │   │               │           │   │       └───categories")
            print("│       │   │               │           │   ├───main")
            print("│       │   │               │           │   ├───multiplayer")
            print("│       │   │               │           │   ├───renderer")
            print("│       │   │               │           │   │   └───entity")
            print("│       │   │               │           │   ├───searchtree")
            print("│       │   │               │           │   └───telemetry")
            print("│       │   │               │           ├───commands")
            print("│       │   │               │           │   ├───arguments")
            print("│       │   │               │           │   │   └───item")
            print("│       │   │               │           │   ├───execution")
            print("│       │   │               │           │   │   └───tasks")
            print("│       │   │               │           │   └───synchronization")
            print("│       │   │               │           ├───core")
            print("│       │   │               │           │   └───registries")
            print("│       │   │               │           ├───data")
            print("│       │   │               │           │   ├───info")
            print("│       │   │               │           │   ├───loot")
            print("│       │   │               │           │   ├───recipes")
            print("│       │   │               │           │   ├───registries")
            print("│       │   │               │           │   └───tags")
            print("│       │   │               │           ├───gametest")
            print("│       │   │               │           │   └───framework")
            print("│       │   │               │           ├───nbt")
            print("│       │   │               │           ├───network")
            print("│       │   │               │           │   ├───chat")
            print("│       │   │               │           │   │   └───numbers")
            print("│       │   │               │           │   ├───protocol")
            print("│       │   │               │           │   │   ├───configuration")
            print("│       │   │               │           │   │   └───game")
            print("│       │   │               │           │   └───syncher")
            print("│       │   │               │           ├───resources")
            print("│       │   │               │           ├───server")
            print("│       │   │               │           │   ├───commands")
            print("│       │   │               │           │   ├───dedicated")
            print("│       │   │               │           │   ├───level")
            print("│       │   │               │           │   └───packs")
            print("│       │   │               │           │       └───linkfs")
            print("│       │   │               │           ├───tags")
            print("│       │   │               │           ├───util")
            print("│       │   │               │           │   └───datafix")
            print("│       │   │               │           │       └───fixes")
            print("│       │   │               │           └───world")
            print("│       │   │               │               ├───entity")
            print("│       │   │               │               │   ├───ai")
            print("│       │   │               │               │   │   ├───behavior")
            print("│       │   │               │               │   │   │   └───warden")
            print("│       │   │               │               │   │   └───gossip")
            print("│       │   │               │               │   ├───animal")
            print("│       │   │               │               │   │   ├───allay")
            print("│       │   │               │               │   │   ├───axolotl")
            print("│       │   │               │               │   │   ├───camel")
            print("│       │   │               │               │   │   ├───frog")
            print("│       │   │               │               │   │   ├───goat")
            print("│       │   │               │               │   │   └───sniffer")
            print("│       │   │               │               │   ├───monster")
            print("│       │   │               │               │   │   ├───breeze")
            print("│       │   │               │               │   │   ├───hoglin")
            print("│       │   │               │               │   │   ├───piglin")
            print("│       │   │               │               │   │   └───warden")
            print("│       │   │               │               │   └───npc")
            print("│       │   │               │               ├───flag")
            print("│       │   │               │               ├───inventory")
            print("│       │   │               │               ├───item")
            print("│       │   │               │               │   └───crafting")
            print("│       │   │               │               ├───level")
            print("│       │   │               │               │   ├───biome")
            print("│       │   │               │               │   ├───block")
            print("│       │       │       │               │   └───loading")
            print("│       │       │       │               ├───energy")
            print("│       │       │       │               ├───entity")
            print("│       │       │       │               ├───event")
            print("│       │       │       │               │   ├───brewing")
            print("│       │       │       │               │   ├───enchanting")
            print("│       │       │       │               │   ├───entity")
            print("│       │       │       │               │   │   ├───item")
            print("│       │       │       │               │   │   ├───living")
            print("│       │       │       │               │   │   └───player")
            print("│       │       │       │               │   ├───furnace")
            print("│       │       │       │               │   ├───level")
            print("│       │       │       │               │   ├───server")
            print("│       │       │       │               │   └───village")
            print("│       │       │       │               ├───fluids")
            print("│       │       │       │               │   └───capability")
            print("│       │       │       │               │       ├───templates")
            print("│       │       │       │               │       └───wrappers")
            print("│       │       │       │               ├───forge")
            print("│       │       │       │               │   └───snapshots")
            print("│       │       │       │               ├───gametest")
            print("│       │       │       │               ├───internal")
            print("│       │       │       │               │   └───versions")
            print("│       │       │       │               │       ├───neoforge")
            print("│       │       │       │               │       └───neoform")
            time.sleep(0.1)
            print("│       │       │       │               ├───items")
            print("│       │       │       │               │   └───wrapper")
            print("│       │       │       │               ├───logging")
            print("│       │       │       │               ├───network")
            print("│       │       │       │               │   ├───bundle")
            print("│       │       │       │               │   ├───configuration")
            print("│       │       │       │               │   ├───connection")
            print("│       │       │       │               │   ├───event")
            print("│       │       │       │               │   ├───filters")
            print("│       │       │       │               │   ├───handlers")
            print("│       │       │       │               │   ├───handling")
            print("│       │       │       │               │   ├───negotiation")
            print("│       │       │       │               │   ├───payload")
            print("│       │       │       │               │   └───registration")
            print("│       │       │       │               ├───registries")
            print("│       │       │       │               │   ├───callback")
            print("│       │       │       │               │   ├───datamaps")
            print("│       │       │       │               │   │   └───builtin")
            print("│       │       │       │               │   └───holdersets")
            print("│       │       │       │               ├───resource")
            print("│       │       │       │               └───server")
            print("│       │       │       │                   ├───command")
            print("│       │       │       │                   │   └───generation")
            print("│       │       │       │                   ├───console")
            print("│       │       │       │                   ├───loading")
            print("│       │       │       │                   ├───permission")
            print("│       │       │       │                   │   ├───events")
            print("│       │       │       │                   │   ├───exceptions")
            print("│       │       │       │                   │   ├───handler")
            print("│       │       │       │                   │   └───nodes")
            print("│       │       │       │                   └───timings")
            print("│       │       │       ├───zip_697194c888aa9726fd47994c0125bbc5")
            print("│       │       │       ├───zip_89653fe82cbf504f752c236cfcf35ec5")
            print("│       │       │       └───zip_cddea7c1872a2cccba75fb8a6eda520c")
            print("│       │       └───neoFormRecompile")
            print("│       ├───gradle")
            print("│       │   └───wrapper")
            print("│       ├───runs")
            print("│       │   ├───client")
            print("│       │   └───server")
            print("│       └───src")
            print("│           └───main")
            print("│               ├───java")
            print("│               │   └───net")
            print("│               │       └───mcreator")
            print("│               │           └───test")
            print("│               └───resources")
            print("│                   ├───assets")
            print("│                   │   └───test")
            print("│                   │       └───lang")
            print("│                   └───META-INF")
            print("├───Muse Hub")
            print("│   ├───Elements")
            print("│   └───Instruments")
            print("├───Music")
            print("├───OneDrive")
            print("│   ├───Attachments")
            print("│   ├───Desktop")
            print("│   │   └───games")
            print("│   ├───Documents")
            print("│   │   ├───GameMakerStudio2")
            print("│   │   │   ├───frog")
            print("│   │   │   │   ├───datafiles")
            print("│   │   │   │   ├───fonts")
            print("│   │   │   │   │   └───f_gamefont")
            print("│   │   │   │   ├───objects")
            print("│   │   │   │   │   ├───o_camera")
            print("│   │   │   │   │   ├───o_game")
            print("│   │   │   │   │   ├───o_player")
            print("│   │   │   │   │   ├───o_slope")
            print("│   │   │   │   │   ├───o_sword")
            print("│   │   │   │   │   └───o_wall")
            print("│   │   │   │   ├───options")
            print("│   │   │   │   │   ├───android")
            print("│   │   │   │   │   ├───html5")
            print("│   │   │   │   │   ├───ios")
            print("│   │   │   │   │   ├───linux")
            print("│   │   │   │   │   ├───mac")
            print("│   │   │   │   │   ├───main")
            print("│   │   │   │   │   ├───operagx")
            print("│   │   │   │   │   ├───tvos")
            print("│   │   │   │   │   └───windows")
            print("│   │   │   │   ├───rooms")
            print("│   │   │   │   │   ├───Room2")
            print("│   │   │   │   │   └───r_testroom")
            print("│   │   │   │   ├───sprites")
            print("│   │   │   │   │   ├───s_background")
            print("│   │   │   │   │   │   └───layers")
            print("│   │   │   │   │   │       └───3c6fec5f-3d5a-457c-9a37-c93aff9251f6")
            print("│   │   │   │   │   ├───s_death")
            print("│   │   │   │   │   │   └───layers")
            print("│   │   │   │   │   │       ├───5373cc33-cf5e-4a50-8e8a-ee3c4fa635b7")
            print("│   │   │   │   │   │       ├───715c8d8f-1ec5-43fb-ae40-b1ece12307cc")
            print("│   │   │   │   │   │       ├───87353a93-1f89-4324-a496-147c303fde32")
            print("│   │   │   │   │   │       ├───9c57c220-155c-4903-b97e-280630580bf7")
            print("│   │   │   │   │   │       └───eae5c5e1-ef08-4818-9943-e085fd1790c0")
            print("│   │   │   │   │   ├───s_emtpy")
            print("│   │   │   │   │   │   └───layers")
            print("│   │   │   │   │   │       └───69f63957-ac28-4ec7-bdbe-5f4566629a90")
            print("│   │   │   │   │   ├───s_newroom")
            print("│   │   │   │   │   │   └───layers")
            print("│   │   │   │   │   │       ├───288da780-b7c6-45e2-ad77-ef85a3209b69")
            print("│   │   │   │   │   │       ├───4fed1b5a-9b3d-468d-b4d7-a7233ab54be3")
            print("│   │   │   │   │   │       ├───64f26d21-6437-4f26-afe7-e6a78449cc12")
            print("│   │   │   │   │   │       ├───85935e79-eb32-4f84-b55e-dc6ad7ab77d9")
            print("│   │   │   │   │   │       ├───86d028f3-5986-4460-96e2-e0b05302974b")
            print("│   │   │   │   │   │       └───ac3feaa4-1e30-4be5-968b-ecc1130902be")
            print("│   │   │   │   │   ├───s_player")
            print("│   │   │   │   │   │   └───layers")
            print("│   │   │   │   │   │       ├───10ebf68d-2dce-4e47-a18b-8ea28b8c590b")
            print("│   │   │   │   │   │       ├───329dd8cd-d4ff-48d4-b144-d6f857c1b99c")
            print("│   │   │   │   │   │       ├───38d14861-51c8-487d-8272-e770431ef529")
            print("│   │   │   │   │   │       └───781b32af-ba05-4d96-b9b5-d52534dca60b")
            print("│   │   │   │   │   ├───s_roomcross")
            print("│   │   │   │   │   │   └───layers")
            print("│   │   │   │   │   │       ├───b6f8d92d-0e08-4679-9d5f-42e5463a1602")
            print("│   │   │   │   │   │       └───efb8e8b5-5ab1-4ccd-a132-7201b5023e56")
            print("│   │   │   │   │   ├───s_slope")
            print("│   │   │   │   │   │   └───layers")
            print("│   │   │   │   │   │       └───37a0042c-c3de-4629-9aae-362185862952")
            print("│   │   │   │   │   ├───s_THEDARKNESSOFREALITY")
            print("│   │   │   │   │   │   └───layers")
            print("│   │   │   │   │   │       └───db3a888a-b230-4973-9c50-c589c58fa591")
            print("│   │   │   │   │   ├───s_wall")
            print("│   │   │   │   │   │   └───layers")
            print("│   │   │   │   │   │       └───37a0042c-c3de-4629-9aae-362185862952")
            print("│   │   │   │   │   ├───s_wing")
            print("│   │   │   │   │   │   └───layers")
            print("│   │   │   │   │   │       └───5d64c96e-0115-4c50-8d2f-1f0321a2288c")
            print("│   │   │   │   │   └───s_word")
            print("│   │   │   │   │       └───layers")
            print("│   │   │   │   │           └───54e3e958-98d8-411f-8884-28e51eb03954")
            print("│   │   │   │   └───tilesets")
            print("│   │   │   │       └───TileSet1")
            print("│   │   │   ├───TemplateProjects")
            print("│   │   │   └───topdown")
            print("│   │   │       ├───datafiles")
            print("│   │   │       ├───options")
            print("│   │   │       │   ├───main")
            print("│   │   │       │   ├───operagx")
            print("│   │   │       │   └───windows")
            print("│   │   │       └───rooms")
            print("│   │   │           └───Room1")
            print("│   │   ├───Rainmeter")
            print("│   │   │   └───Skins")
            print("│   │   │       ├───@Vault")
            print("│   │   │       │   └───Plugins")
            print("│   │   │       ├───illustro")
            print("│   │   │       │   ├───@Resources")
            print("│   │   │       │   ├───Clock")
            print("│   │   │       │   ├───Disk")
            print("│   │   │       │   ├───Google")
            print("│   │   │       │   ├───Network")
            print("│   │   │       │   ├───Recycle Bin")
            print("│   │   │       │   ├───System")
            print("│   │   │       │   └───Welcome")
            print("│   │   │       ├───Mond")
            print("│   │   │       │   ├───@Resources")
            print("│   │   │       │   │   ├───Addons")
            print("│   │   │       │   │   ├───Fonts")
            print("│   │   │       │   │   ├───Language")
            print("│   │   │       │   │   └───WeatherIcons")
            print("│   │   │       │   ├───Clock")
            print("│   │   │       │   ├───Player")
            print("│   │   │       │   ├───Recycle Bin")
            print("│   │   │       │   ├───Settings")
            print("│   │   │       │   └───Weather")
            print("│   │   │       └───TaskbarX")
            print("│   │   │           └───Release")
            print("│   │   │               └───app.publish")
            print("│   │   ├───Unreal Projects")
            print("│   │   ├───Virtual Machines")
            print("│   │   │   ├───Other Linux 6.x kernel 64-bit")
            print("│   │   │   │   └───Other Linux 6.x kernel 64-bit.vmrest.lck")
            print("│   │   │   └───Other Linux 6.x kernel 64-bit (2)")
            print("│   │   └───WhirlwindFX")
            print("│   │       ├───Components")
            print("│   │       ├───Effects")
            print("│   │       ├───Macroscripts")
            time.sleep(0.1)
            print("│   │       │   ├───Actions")
            print("│   │       │   └───Inputs")
            print("│   │       └───Plugins")
            print("│   ├───Pictures")
            print("│   │   ├───Camera Roll")
            print("│   │   ├───MSI Wallpaper")
            print("│   │   ├───Saved Pictures")
            print("│   │   └───Screenshots")
            print("│   └───Videos")
            print("│       ├───Captures")
            print("│       ├───Fortnite")
            print("│       └───SteelSeries Moments")
            print("│           ├───Exported Clips")
            print("│           ├───Shared Clips")
            print("│           └───thumbs")
            print("├───Pictures")
            print("│   ├───All Posy's Cursors 1.4")
            print("│   │   ├───Posy's Cursor")
            print("│   │   ├───Posy's Cursor Black")
            print("│   │   ├───Posy's Cursor Black for 125 and 175 percent")
            print("│   │   ├───Posy's Cursor Black Point Outside")
            print("│   │   ├───Posy's Cursor extras")
            print("│   │   │   └───Max 128 versions")
            print("│   │   ├───Posy's Cursor for 125 and 175 percent")
            print("│   │   ├───Posy's Cursor Mono")
            print("│   │   ├───Posy's Cursor Mono Black")
            print("│   │   └───Posy's Cursor Strokeless")
            print("│   ├───Camera Roll")
            print("│   ├───Saved Pictures")
            print("│   ├───Screenshots")
            print("│   └───VRChat")
            print("├───Saved Games")
            print("│   ├───Respawn")
            print("│   │   └───Apex")
            print("│   │       ├───assets")
            print("│   │       │   ├───patch")
            print("│   │       │   │   └───paks")
            print("│   │       │   │       └───Win64")
            print("│   │       │   ├───s2")
            print("│   │       │   │   ├───promo")
            print("│   │       │   │   └───store")
            print("│   │       │   └───temp")
            print("│   │       │       └───cameraslots")
            print("│   │       ├───local")
            print("│   │       └───profile")
            print("│   └───Tiny Glade")
            print("│       ├───cas-cache")
            print("│       │   ├───62e116739a9ea2fbf93ae76801aa78973da68602f842a8b8a49658d3dd7016e9")
            print("│       │   │   └───snapshots")
            print("│       │   └───879dfa80318345e15c58c404245270c5f258dacc1520589df60e0c9f73dc0070")
            print("│       │       └───snapshots")
            print("│       └───Steam")
            print("│           └───76561199384084802")
            print("│               ├───deleted-saves")
            print("│               ├───saves")
            print("│               │   └───394c102f-402c-4cce-9285-b2445dff9370")
            print("│               │       └───snapshots")
            print("│               ├───screenshots")
            print("│               └───tmp")
            print("├───Searches")
            print("├───source")
            print("│   └───repos")
            print("│       └───test")
            print("│           ├───test")
            print("│           │   └───x64")
            print("│           │       └───Debug")
            print("│           │           └───test.tlog")
            print("│           └───x64")
            print("│               └───Debug")
            print("└───Videos")
            print("    ├───.gallery")
            print("    │   └───e648eb04-f9ea-43eb-8a56-e707f69b33d2")
            print("    ├───CacheClip")
            print("    │   └───audio")
            print("    │       ├───C_")
            print("    │       │   └───Users")
            print("    │       │       └───potato")
            print("    │       │           ├───Downloads")
            print("    │       │           └───Videos")
            print("    │       └───fairlightProfiles")
            print("    │           ├───1")
            print("    │           └───a")
            print("    ├───Captures")
            print("    ├───Fortnite")
            print("    ├───Overwolf")
            print("    │   ├───BUFF")
            print("    │   └───Buff Achievement Tracker")
            print("    ├───Resolve Project Backups")
            print("    └───SteelSeries Moments")
            print("        ├───Exported Clips")
            print("        └───Shared Clips")
            n()
            print("Scan Complete. Results Below.")
            n()
            print("Safe Files: 18,603")
            print("Suspicious Files: 0")
            print("Dangerous Files: 0")
        else:
            thatdidntwork()

    elif choice == "netstat":
        willitrun = random.randint(0,7)
        if willitrun > 1:
            print("Active Connections")
            print(f"  Proto  Local Address          Foreign Address        State")
            print(f"  TCP    127.0.0.1:6327         {user}:49304            ESTABLISHED (Confirmed by Microsoft as SAFE!)")
            print(f"  TCP    127.0.0.1:6327         {user}:49362            ESTABLISHED (Confirmed by Microsoft as SAFE!)")
            print(f"  TCP    127.0.0.1:6327         {user}:53186            ESTABLISHED (Confirmed by Microsoft as SAFE!)")
            print(f"  TCP    127.0.0.1:6327         {user}:53187            ESTABLISHED (Confirmed by Microsoft as SAFE!)")
            print(f"  TCP    127.0.0.1:6327         {user}:53189            ESTABLISHED (Confirmed by Microsoft as SAFE!)")
            print(f"  TCP    127.0.0.1:6327         {user}:53229            ESTABLISHED (Confirmed by Microsoft as SAFE!)")
            print(f"  TCP    127.0.0.1:6327         {user}:53235            ESTABLISHED (Confirmed by Microsoft as SAFE!)")
            print(f"  TCP    127.0.0.1:6327         {user}:53237            ESTABLISHED (Confirmed by Microsoft as SAFE!)")
            print(f"  TCP    127.0.0.1:27060        {user}:57344            ESTABLISHED (Confirmed by Microsoft as SAFE!)")
            print(f"  TCP    127.0.0.1:49304        {user}:6327             ESTABLISHED (Confirmed by Microsoft as SAFE!)")
            print(f"  TCP    127.0.0.1:49355        {user}:53185            ESTABLISHED (Confirmed by Microsoft as SAFE!)")
            print(f"  TCP    127.0.0.1:49362        {user}:6327             ESTABLISHED (Confirmed by Microsoft as SAFE!)")
            print(f"  TCP    127.0.0.1:52769        {user}:65001            ESTABLISHED (Confirmed by Microsoft as SAFE!)")
            print(f"  TCP    127.0.0.1:52985        {user}:57945            ESTABLISHED (Confirmed by Microsoft as SAFE!)")
            print(f"  TCP    127.0.0.1:53185        {user}:49355            ESTABLISHED (Confirmed by Microsoft as SAFE!)")
            print(f"  TCP    127.0.0.1:53185        {user}:53234            ESTABLISHED (Confirmed by Microsoft as SAFE!)")
            print(f"  TCP    127.0.0.1:53185        {user}:53236            ESTABLISHED (Confirmed by Microsoft as SAFE!)")
            print(f"  TCP    127.0.0.1:53185        {user}:53238            ESTABLISHED (Confirmed by Microsoft as SAFE!)")
            print(f"  TCP    127.0.0.1:53185        {user}:58219            ESTABLISHED (Confirmed by Microsoft as SAFE!)")
            print(f"  TCP    127.0.0.1:53186        {user}:6327             ESTABLISHED (Confirmed by Microsoft as SAFE!)")
            print(f"  TCP    127.0.0.1:53187        {user}:6327             ESTABLISHED (Confirmed by Microsoft as SAFE!)")
            print(f"  TCP    127.0.0.1:53189        {user}:6327             ESTABLISHED (Confirmed by Microsoft as SAFE!)")
            print(f"  TCP    127.0.0.1:53229        {user}:6327             ESTABLISHED (Confirmed by Microsoft as SAFE!)")
            print(f"  TCP    127.0.0.1:53231        {user}:53239            ESTABLISHED (Confirmed by Microsoft as SAFE!)")
            print(f"  TCP    127.0.0.1:53234        {user}:53185            ESTABLISHED (Confirmed by Microsoft as SAFE!)")
            print(f"  TCP    127.0.0.1:53235        {user}:6327             ESTABLISHED (Confirmed by Microsoft as SAFE!)")
            print(f"  TCP    127.0.0.1:53236        {user}:53185            ESTABLISHED (Confirmed by Microsoft as SAFE!)")
            print(f"  TCP    127.0.0.1:53237        {user}:6327             ESTABLISHED (Confirmed by Microsoft as SAFE!)")
            print(f"  TCP    127.0.0.1:53238        {user}:53185            ESTABLISHED (Confirmed by Microsoft as SAFE!)")
            print(f"  TCP    127.0.0.1:53239        {user}:53231            ESTABLISHED (Confirmed by Microsoft as SAFE!)")
            print(f"  TCP    127.0.0.1:54248        {user}:54249            ESTABLISHED (Confirmed by Microsoft as SAFE!)")
            print(f"  TCP    127.0.0.1:54249        {user}:54248            ESTABLISHED (Confirmed by Microsoft as SAFE!)")
            print(f"  TCP    127.0.0.1:54250        {user}:54251            ESTABLISHED (Confirmed by Microsoft as SAFE!)")
            print(f"  TCP    127.0.0.1:54251        {user}:54250            ESTABLISHED (Confirmed by Microsoft as SAFE!)")
            print(f"  TCP    127.0.0.1:57300        {user}:57316            ESTABLISHED (Confirmed by Microsoft as SAFE!)")
            print(f"  TCP    127.0.0.1:57301        {user}:57315            ESTABLISHED (Confirmed by Microsoft as SAFE!)")
            print(f"  TCP    127.0.0.1:57315        {user}:57301            ESTABLISHED (Confirmed by Microsoft as SAFE!)")
            print(f"  TCP    127.0.0.1:57316        {user}:57300            ESTABLISHED (Confirmed by Microsoft as SAFE!)")
            print(f"  TCP    127.0.0.1:57344        {user}:27060            ESTABLISHED (Confirmed by Microsoft as SAFE!)")
            print(f"  TCP    127.0.0.1:57945        {user}:52985            ESTABLISHED (Confirmed by Microsoft as SAFE!)")
            print(f"  TCP    127.0.0.1:58219        {user}:53185            ESTABLISHED (Confirmed by Microsoft as SAFE!)")
            print(f"  TCP    192.168.0.23:65001        {user}:52769            ESTABLISHED (Confirmed by Microsoft as SAFE!)")

            try:
                while True:
                    time.sleep(random.randint(0,10))
                    randomport = random.randint(00000,99999)
                    random2digit = random.randint(00,99)
                    print(f"  TCP    127.0.0.1:{randomport}        sea{random2digit}s{random2digit}-in-f4:https            ESTABLISHED (Confirmed by Microsoft as SAFE!)")
            except KeyboardInterrupt:
                print("")
                os.system("cls")
        else:
            thatdidntwork()

    elif choice == "ipconfig":
        willitrun = random.randint(0,7)
        if willitrun > 1:
            print("Windows IP Configuration")
            n()
            n()
            print("Ethernet adapter Ethernet:")
            n()
            print("   Media State . . . . . . . . . . . : Media disconnected")
            print("   Connection-specific DNS Suffix  . :")
            n()
            print("Wireless LAN adapter Local Area Connection* 9:")
            n()
            print("   Media State . . . . . . . . . . . : Media disconnected")
            print("   Connection-specific DNS Suffix  . :")
            n()
            print("Wireless LAN adapter Local Area Connection* 10:")
            n()
            print("   Media State . . . . . . . . . . . : Media disconnected")
            print("   Connection-specific DNS Suffix  . :")
            n()
            print("Ethernet adapter VMware Network Adapter VMnet1:")
            n()
            print("   Connection-specific DNS Suffix  . :")
            print("   Link-local IPv6 Address . . . . . : fe80::1d0:67a8:38ca:a3e3%17")
            print("   IPv4 Address. . . . . . . . . . . : 192.168.142.1")
            print("   Subnet Mask . . . . . . . . . . . : 255.255.255.0")
            print("   Default Gateway . . . . . . . . . :")
            n()
            print("Ethernet adapter VMware Network Adapter VMnet8:")
            n()
            print("   Connection-specific DNS Suffix  . :")
            print("   Link-local IPv6 Address . . . . . : fe80::fca2:89c4:248c:7d92%11")
            print("   IPv4 Address. . . . . . . . . . . : 192.168.136.1")
            print("   Subnet Mask . . . . . . . . . . . : 255.255.255.0")
            print("   Default Gateway . . . . . . . . . :")
            n()
            print("Wireless LAN adapter Wi-Fi:")
            n()
            print("   Connection-specific DNS Suffix  . : home")
            print("   Link-local IPv6 Address . . . . . : fe80::2add:d4f0:189d:11bf%4")
            print("   IPv4 Address. . . . . . . . . . . : 192.168.0.23")
            print("   Subnet Mask . . . . . . . . . . . : 255.255.255.0")
            print("   Default Gateway . . . . . . . . . : 192.168.0.1")
            n()
            print("Ethernet adapter Bluetooth Network Connection:")
            n()
            print("   Media State . . . . . . . . . . . : Media disconnected")
            print("   Connection-specific DNS Suffix  . :")
            n()
            print("Ethernet adapter vEthernet (WSL (Hyper-V firewall)):")
            n()
            print("   Connection-specific DNS Suffix  . :")
            print("   Link-local IPv6 Address . . . . . : fe80::7a4a:b809:2a03:a136%46")
            print("   IPv4 Address. . . . . . . . . . . : 172.21.16.1")
            print("   Subnet Mask . . . . . . . . . . . : 255.255.240.0")
            print("   Default Gateway . . . . . . . . . :")
            n()
            print("All IP addresses scanned. Results Below.")
            n()
            print("Safe Connections: 8")
            print("Suspicious Connections: 0")
            print("Dangerous Connections: 0")
        else:
            thatdidntwork()

    elif choice == "assoc":
        willitrun = random.randint(0,7)
        if willitrun > 1:
            print(".001=WinRAR")
            print(".386=vxdfile")
            print(".3g2=WMP11.AssocFile.3G2")
            print(".3gp=WMP11.AssocFile.3GP")
            print(".3gp2=WMP11.AssocFile.3G2")
            print(".3gpp=WMP11.AssocFile.3GP")
            print(".7z=WinRAR")
            print(".8ba=Photoshop.PlugIn")
            print(".8bc=Photoshop.PlugIn")
            print(".8bs=Photoshop.PlugIn")
            print(".8bx=Photoshop.PlugIn")
            print(".8by=Photoshop.PlugIn")
            print(".8li=Photoshop.PlugIn")
            print(".AAC=WMP11.AssocFile.ADTS")
            print(".abr=Photoshop.BrushesFile")
            print(".acb=Adobe.Illustrator.ColorBook")
            print(".shh=Photoshop.SHHFile.190")
            print(".shproj=VisualStudio.Launcher.shproj.15.0")
            print(".shtml=shtmlfile")
            print(".sldm=PowerPoint.SlideMacroEnabled.12")
            print(".sldx=PowerPoint.Slide.12")
            print(".slk=Excel.SLK")
            print(".sln=VisualStudio.Launcher.sln")
            print(".slnf=VisualStudio.Launcher.slnf")
            print(".smrd=Adobe.Illustrator.Filter")
            print(".snd=WMP11.AssocFile.AU")
            print(".snk=VisualStudio.snk.81ecd5a7")
            print(".spc=SPCFile")
            print(".sst=CertificateStoreFile")
            print(".sta=Photoshop.STAFile.190")
            print(".stvproj=VisualStudio.StvProj.10")
            print(".suo=VisualStudio.Launcher.suo")
            print(".svclog=VisualStudio.SvcLog.10")
            print("._vcsxsln80=VisualStudio.Launcher._vcsxsln80")
            print("._vcsxsln90=VisualStudio.Launcher._vcsxsln90")
            print("._vjsxsln80=VisualStudio.Launcher._vjsxsln80")
            print("._vw8xsln110=VisualStudio.Launcher._vw8xsln110")
            print("._vwdxsln100=VisualStudio.Launcher._vwdxsln100")
            print("._vwdxsln110=VisualStudio.Launcher._vwdxsln110")
            print("._vwdxsln120=VisualStudio.Launcher._vwdxsln120")
            print(".sst=CertificateStoreFile")
            print(".sta=Photoshop.STAFile.190")
            print(".stvproj=VisualStudio.StvProj.10")
            print(".suo=VisualStudio.Launcher.suo")
            print(".svclog=VisualStudio.SvcLog.10")
            print("._vcsxsln80=VisualStudio.Launcher._vcsxsln80")
            print("._vcsxsln90=VisualStudio.Launcher._vcsxsln90")
            print("._vjsxsln80=VisualStudio.Launcher._vjsxsln80")
            print("._vw8xsln110=VisualStudio.Launcher._vw8xsln110")
            print("._vwdxsln100=VisualStudio.Launcher._vwdxsln100")
            print("._vwdxsln110=VisualStudio.Launcher._vwdxsln110")
            print("._vwdxsln120=VisualStudio.Launcher._vwdxsln120")
            print(".sst=CertificateStoreFile")
            print(".sta=Photoshop.STAFile.190")
            print(".stvproj=VisualStudio.StvProj.10")
            print(".suo=VisualStudio.Launcher.suo")
            print(".svclog=VisualStudio.SvcLog.10")
            print("._vcsxsln80=VisualStudio.Launcher._vcsxsln80")
            print("._vcsxsln90=VisualStudio.Launcher._vcsxsln90")
            print("._vjsxsln80=VisualStudio.Launcher._vjsxsln80")
            print("._vw8xsln110=VisualStudio.Launcher._vw8xsln110")
            print("._vwdxsln100=VisualStudio.Launcher._vwdxsln100")
            print("._vwdxsln110=VisualStudio.Launcher._vwdxsln110")
            print("._vwdxsln120=VisualStudio.Launcher._vwdxsln120")
            print("._vwdxsln140=VisualStudio.Launcher._vwdxsln140")
            print("._vwdxsln150=VisualStudio.Launcher._vwdxsln150")
            print("._vwdxsln80=VisualStudio.Launcher._vwdxsln80")
            print("._vwdxsln90=VisualStudio.Launcher._vwdxsln90")
            print("._vwinxsln120=VisualStudio.Launcher._vwinxsln120")
            print("._vwinxsln140=VisualStudio.Launcher._vwinxsln140")
            print("._vwinxsln150=VisualStudio.Launcher._vwinxsln150")
            print("._wdxsln110=VisualStudio.Launcher._wdxsln110")
            print("._wdxsln120=VisualStudio.Launcher._wdxsln120")
            print("._wdxsln140=VisualStudio.Launcher._wdxsln140")
            print("._wdxsln150=VisualStudio.Launcher._wdxsln150")
            print(".001=WinRAR")
            print(".386=vxdfile")
            print(".3g2=WMP11.AssocFile.3G2")
            print(".3gp=WMP11.AssocFile.3GP")
            print(".3gp2=WMP11.AssocFile.3G2")
            print(".3gpp=WMP11.AssocFile.3GP")
            print(".7z=WinRAR")
            print(".8ba=Photoshop.PlugIn")
            print(".8bc=Photoshop.PlugIn")
            print(".8bs=Photoshop.PlugIn")
            print(".8bx=Photoshop.PlugIn")
            print(".8by=Photoshop.PlugIn")
            print(".8li=Photoshop.PlugIn")
            print(".AAC=WMP11.AssocFile.ADTS")
            print(".abr=Photoshop.BrushesFile")
            print(".acb=Adobe.Illustrator.ColorBook")
            print(".shh=Photoshop.SHHFile.190")
            print(".shproj=VisualStudio.Launcher.shproj.15.0")
            print(".shtml=shtmlfile")
            print(".sldm=PowerPoint.SlideMacroEnabled.12")
            print(".sldx=PowerPoint.Slide.12")
            print(".slk=Excel.SLK")
            print(".sln=VisualStudio.Launcher.sln")
            print(".slnf=VisualStudio.Launcher.slnf")
            print(".smrd=Adobe.Illustrator.Filter")
            print(".snd=WMP11.AssocFile.AU")
            print(".snk=VisualStudio.snk.81ecd5a7")
            print(".spc=SPCFile")
            print(".sst=CertificateStoreFile")
            print(".sta=Photoshop.STAFile.190")
            print(".stvproj=VisualStudio.StvProj.10")
            print(".suo=VisualStudio.Launcher.suo")
            print(".svclog=VisualStudio.SvcLog.10")
            print("._vcsxsln80=VisualStudio.Launcher._vcsxsln80")
            print("._vcsxsln90=VisualStudio.Launcher._vcsxsln90")
            print("._vjsxsln80=VisualStudio.Launcher._vjsxsln80")
            print("._vw8xsln110=VisualStudio.Launcher._vw8xsln110")
            print("._vwdxsln100=VisualStudio.Launcher._vwdxsln100")
            print("._vwdxsln110=VisualStudio.Launcher._vwdxsln110")
            print("._vwdxsln120=VisualStudio.Launcher._vwdxsln120")
            print(".sst=CertificateStoreFile")
            print(".sta=Photoshop.STAFile.190")
            print(".stvproj=VisualStudio.StvProj.10")
            print(".suo=VisualStudio.Launcher.suo")
            print(".svclog=VisualStudio.SvcLog.10")
            print("._vcsxsln80=VisualStudio.Launcher._vcsxsln80")
            print("._vcsxsln90=VisualStudio.Launcher._vcsxsln90")
            print("._vjsxsln80=VisualStudio.Launcher._vjsxsln80")
            print("._vw8xsln110=VisualStudio.Launcher._vw8xsln110")
            print("._vwdxsln100=VisualStudio.Launcher._vwdxsln100")
            print("._vwdxsln110=VisualStudio.Launcher._vwdxsln110")
            print("._vwdxsln120=VisualStudio.Launcher._vwdxsln120")
            print(".sst=CertificateStoreFile")
            print(".sta=Photoshop.STAFile.190")
            print(".stvproj=VisualStudio.StvProj.10")
            print(".suo=VisualStudio.Launcher.suo")
            print(".svclog=VisualStudio.SvcLog.10")
            print("._vcsxsln80=VisualStudio.Launcher._vcsxsln80")
            print("._vcsxsln90=VisualStudio.Launcher._vcsxsln90")
            print("._vjsxsln80=VisualStudio.Launcher._vjsxsln80")
            print("._vw8xsln110=VisualStudio.Launcher._vw8xsln110")
            print("._vwdxsln100=VisualStudio.Launcher._vwdxsln100")
            print("._vwdxsln110=VisualStudio.Launcher._vwdxsln110")
            print("._vwdxsln120=VisualStudio.Launcher._vwdxsln120")
            print("._vwdxsln140=VisualStudio.Launcher._vwdxsln140")
            print("._vwdxsln150=VisualStudio.Launcher._vwdxsln150")
            print("._vwdxsln80=VisualStudio.Launcher._vwdxsln80")
            print("._vwdxsln90=VisualStudio.Launcher._vwdxsln90")
            print("._vwinxsln120=VisualStudio.Launcher._vwinxsln120")
            print("._vwinxsln140=VisualStudio.Launcher._vwinxsln140")
            print("._vwinxsln150=VisualStudio.Launcher._vwinxsln150")
            print("._wdxsln110=VisualStudio.Launcher._wdxsln110")
            print("._wdxsln120=VisualStudio.Launcher._wdxsln120")
            print("._wdxsln140=VisualStudio.Launcher._wdxsln140")
            print("._wdxsln150=VisualStudio.Launcher._wdxsln150")
            print(".001=WinRAR")
            print(".386=vxdfile")
            print(".3g2=WMP11.AssocFile.3G2")
            print(".3gp=WMP11.AssocFile.3GP")
            print(".3gp2=WMP11.AssocFile.3G2")
            print(".3gpp=WMP11.AssocFile.3GP")
            print(".7z=WinRAR")
            print(".8ba=Photoshop.PlugIn")
            print(".8bc=Photoshop.PlugIn")
            print(".8bs=Photoshop.PlugIn")
            print(".8bx=Photoshop.PlugIn")
            print(".8by=Photoshop.PlugIn")
            print(".8li=Photoshop.PlugIn")
            print(".AAC=WMP11.AssocFile.ADTS")
            print(".abr=Photoshop.BrushesFile")
            print(".acb=Adobe.Illustrator.ColorBook")
            print(".shh=Photoshop.SHHFile.190")
            print(".shproj=VisualStudio.Launcher.shproj.15.0")
            print(".shtml=shtmlfile")
            print(".sldm=PowerPoint.SlideMacroEnabled.12")
            print(".sldx=PowerPoint.Slide.12")
            print(".slk=Excel.SLK")
            print(".sln=VisualStudio.Launcher.sln")
            print(".slnf=VisualStudio.Launcher.slnf")
            print(".smrd=Adobe.Illustrator.Filter")
            print(".snd=WMP11.AssocFile.AU")
            print(".snk=VisualStudio.snk.81ecd5a7")
            print(".spc=SPCFile")
            print(".sst=CertificateStoreFile")
            print(".sta=Photoshop.STAFile.190")
            print(".stvproj=VisualStudio.StvProj.10")
            print(".suo=VisualStudio.Launcher.suo")
            print(".svclog=VisualStudio.SvcLog.10")
            print("._vcsxsln80=VisualStudio.Launcher._vcsxsln80")
            print("._vcsxsln90=VisualStudio.Launcher._vcsxsln90")
            print("._vjsxsln80=VisualStudio.Launcher._vjsxsln80")
            print("._vw8xsln110=VisualStudio.Launcher._vw8xsln110")
            print("._vwdxsln100=VisualStudio.Launcher._vwdxsln100")
            print("._vwdxsln110=VisualStudio.Launcher._vwdxsln110")
            print("._vwdxsln120=VisualStudio.Launcher._vwdxsln120")
            print(".sst=CertificateStoreFile")
            print(".sta=Photoshop.STAFile.190")
            print(".stvproj=VisualStudio.StvProj.10")
            print(".suo=VisualStudio.Launcher.suo")
            print(".svclog=VisualStudio.SvcLog.10")
            print("._vcsxsln80=VisualStudio.Launcher._vcsxsln80")
            print("._vcsxsln90=VisualStudio.Launcher._vcsxsln90")
            print("._vjsxsln80=VisualStudio.Launcher._vjsxsln80")
            print("._vw8xsln110=VisualStudio.Launcher._vw8xsln110")
            print("._vwdxsln100=VisualStudio.Launcher._vwdxsln100")
            print("._vwdxsln110=VisualStudio.Launcher._vwdxsln110")
            print("._vwdxsln120=VisualStudio.Launcher._vwdxsln120")
            print(".sst=CertificateStoreFile")
            print(".sta=Photoshop.STAFile.190")
            print(".stvproj=VisualStudio.StvProj.10")
            print(".suo=VisualStudio.Launcher.suo")
            print(".svclog=VisualStudio.SvcLog.10")
            print("._vcsxsln80=VisualStudio.Launcher._vcsxsln80")
            print("._vcsxsln90=VisualStudio.Launcher._vcsxsln90")
            print("._vjsxsln80=VisualStudio.Launcher._vjsxsln80")
            print("._vw8xsln110=VisualStudio.Launcher._vw8xsln110")
            print("._vwdxsln100=VisualStudio.Launcher._vwdxsln100")
            print("._vwdxsln110=VisualStudio.Launcher._vwdxsln110")
            print("._vwdxsln120=VisualStudio.Launcher._vwdxsln120")
            print("._vwdxsln140=VisualStudio.Launcher._vwdxsln140")
            print("._vwdxsln150=VisualStudio.Launcher._vwdxsln150")
            print("._vwdxsln80=VisualStudio.Launcher._vwdxsln80")
            print("._vwdxsln90=VisualStudio.Launcher._vwdxsln90")
            print("._vwinxsln120=VisualStudio.Launcher._vwinxsln120")
            print("._vwinxsln140=VisualStudio.Launcher._vwinxsln140")
            print("._vwinxsln150=VisualStudio.Launcher._vwinxsln150")
            print("._wdxsln110=VisualStudio.Launcher._wdxsln110")
            print("._wdxsln120=VisualStudio.Launcher._wdxsln120")
            print("._wdxsln140=VisualStudio.Launcher._wdxsln140")
            print("._wdxsln150=VisualStudio.Launcher._wdxsln150")
            n()
            print("All file associations scanned. Results below.")
            n()
            print("Safe Files: 403")
            print("Suspicious Files: 0")
            print("Dangerous Files: 0")
        else:
            thatdidntwork()

    elif choice == "chkdsk":
        willitrun = random.randint(0,7)
        if willitrun > 1:
            print("The type of the file system is NTFS.")
            time.sleep(1)
            print("Running CHKDSK in read-only mode.")
            print("Stage 1: Examining basic file system structure ...")
            print("  1670400 file records processed.")
            print("File verification completed.")
            print(" Phase duration (File record verification): 7.52 seconds.")
            print("  29481 large file records processed.")
            print(" Phase duration (Orphan file record recovery): 12.82 milliseconds.")
            print("  0 bad file records processed.")
            print(" Phase duration (Bad file record checking): 0.32 milliseconds.")
            n()
            print("No harmful files found!")
            n()
            time.sleep(1)
            print("Stage 2: Examining file name linkage ...")
            print("  958 reparse records processed.")
            print("  2143194 index entries processed.")
            print("Index verification completed.")
            print(" Phase duration (Index verification): 21.22 seconds.")
            print("CHKDSK is scanning unindexed files for reconnect to their original directory.")
            n()
            print("No harmful files found!")
            n()
            time.sleep(1)
            print("Stage 3: Examining security descriptors ...")
            print("Security descriptor verification completed.")
            print(" Phase duration (Security descriptor verification): 40.16 milliseconds.")
            print("  236398 data files processed.")
            print(" Phase duration (Data attribute verification): 0.54 milliseconds.")
            print("CHKDSK is verifying Usn Journal...")
            print("Usn Journal verification completed.")
            n()
            print("Windows has checked the file system and found no problems!")
            n()
            print("1298853452 KB total disk space.")
            print(" 819373356 KB in 983299 files.")
            print("    624408 KB in 236399 indexes.")
            print("         0 KB in bad sectors.")
            print("   1827936 KB in use by the system.")
            print("     65536 KB occupied by the log file.")
            print(" 477027752 KB available on disk.")
            n()
            print("      4096 bytes in each allocation unit.")
            print(" 324713363 total allocation units on disk.")
            print(" 119256938 allocation units available on disk.")
            n()
            print("Total duration: 45.23 seconds (45233 ms).")

    elif choice == "msconfig":
        thatdidntwork()

    elif choice == "whoami":
        print("User/SCAMMER001")

    elif choice.startswith("ping"):
        print("Pinging secure IP Address...")
        time.sleep(random.randint(3,7))
        print("No viruses or hackers found!")

    else:
        print(f"'{choice}' is not recognized as an internal or external command,")
        print("operable program or batch file.")
